### ISSUE TITLE
Suspended tabs recently turned blank white. Extension options open all blank page as well.

### ISSUE THREAD

**Issue by macsunmood** [gioxx/MarvellousSuspender#121]
* Extension version: 7.1.6.2
 * Browser name & version: Chrome 90.0.4430.212
 * Operating system & version: Win10

Found the same issue is being reported by other users in the Chome Webstore
![image](https://user-images.githubusercontent.com/45285672/120789598-7b292080-c53a-11eb-9bb8-e65caebe37c0.png)

Any workaround ?

**Comment by dotkeenan** [comment]
Can confirm this is happening to me as well.

**Comment by ZornTaov** [comment]
a workaround I've found is to close all windows except the options page (if you can get it to load) and load the previous valid session, which will load the already suspended tabs correctly and suspends any unsuspended tabs, which helps with the memory load I guess.  Unfortunately #76 happens when you do this.

**Comment by neviln** [comment]
This just happened to me as well. Please tell me there's a different workaround since my last valid session doesn't appear to be up-to-date as Chrome crashed today and didn't exit properly. So the tab-count showing on the options page for my last valid session appears to be less than it should be.
----------
UPDATE: Luckily I also have the SessionBuddy extension installed and fortunately, it had done an automatic backup of my Chrome session from a few hours earlier. But when I tried to test if restoring one of my chrome windows from the SessionBuddy saved session would work, I still got the same blank, white pages. However, once I fully closed ALL the suspended tabs that had the blank, white pages and then restarted Chrome, I was successfully able to restore the SessionBuddy saved session and got all my tabs back in their proper suspended states. 
I'm mentioning this option for anyone else with this issue that had A TON of suspended tabs open. The other fix mentioned in the comments was to reload the MarvellousSuspender's saved session, but that method would reload all your tabs in the UN-suspended state and would be a massive hit on the computer's resources. However, using SessionBuddy bypassed that concern by reloading the session with all previously suspended tabs back in their suspended states. However, the only downside is that all my tabs that were in Chrome Groups were ungrouped, but that was a relatively easy fix.

**Comment by briantully** [comment]
This started happening to me today as well. Even stranger that it's only some of the suspended tabs that lose their favicon and only display a blank white page instead of the default "refresh of click to reload" placeholder page. Under "Manage Extensions" I'm not seeing any Javascript errors with Developer Mode enabled. It's a head scratcher.

**Comment by jafin** [comment]
Workaround for Chrome91+ 
* Go to Google menu > Settings > Extensions > Mravellous Suspender Extension > Details 
* Turn on "Allow access to file URLs"


Hoping this is a short term hack and not required long term, as it seems to be excessive permissions if so.

Quick scan of the codebase, it doesn't make much sense the above even works, the favicon is encoded, not stored via file:// ... So unsure about this.

EDIT I doubt this really is any hard fix, just a side effect that *sometimes* triggers the page restore.. YMMV
EDIT2: See note from bobSage123. For me, tabs are working fine again in Chrome 91.0.4472.106. No change required.

**Comment by macsunmood** [comment]
Looks like updating Chrome to the latest stable version (91.0.4472.77) worked for me. Everything's just fine so far.

**Comment by lateparty** [comment]
I'm on Version 91.0.4472.77 (Official Build) Arch Linux (64-bit) and still definitely get it. #125 appears to be the exact same issue and his workaround works, but not as well as the one listed above by @jafin which effectively resolves the issue.

**Comment by bobsage123** [comment]
> I'm on Version 91.0.4472.77 (Official Build) Arch Linux (64-bit) and still definitely get it. #125 appears to be the exact same issue and his workaround works, but not as well as the one listed above by @jafin which effectively resolves the issue.

Same

**Comment by bobsage123** [comment]
> Workaround for Chrome91+
> 
> * Go to Google menu > Settings > Extensions > Mravellous Suspender Extension > Details
> * Turn on "Allow access to file URLs"
> 
> Hoping this is a short term hack and not required long term, as it seems to be excessive permissions if so.
> 
> Quick scan of the codebase, it doesn't make much sense the above even works, the favicon is encoded, not stored via file:// ... So unsure about this.

Thank you. This fixed my problem. Was also having an issue with watching youtube videos lagging due to buggy suspender and this fixed that too.

**Comment by Gyumaou** [comment]
I'm on Version 91.0.4472.77 (Official Build) (64-bit) too and still happening. 

Restoring full session works for sure, and doesn't take too long. Unsuspending tab from menu also works, so a more memory-intensive option is to use Unsuspend All Tabs in All Windows. Somehow even if the page view is broken the unsuspend action works.

**Comment by GeezrRckr** [comment]
+1 on this problem happening to me with Chrome Version 91.0.4472.77 (Official Build) (64-bit).

+1 on the @jafin workaround fix.

Hope the developers get on this asap.  Love this extension!  Thx.

**Comment by nihaals** [comment]
I already had `Allow access to file URLs` enabled but toggling it off and back on worked (and is much faster than unsuspending and suspending again). It did delete my tab groups though.

**Comment by GeezrRckr** [comment]
This has become a truly annoying bug.   Like most of us, I keep a bunch of tabs open when I close/reopen Chrome.  After doing the @jafin hack, reopening Chrome after a shutdown brings back the same behavior of lost URLs as before.  I had to go in and re toggle and then go into history and reopen the group of tabs (because when you re toggle AFTER a shut down, the tabs disappear in that window).

Does anyone have a line to the developer?  We really need to get a fix on this asap (please).

**Comment by bobsage123** [comment]
> This has become a truly annoying bug. Like most of us, I keep a bunch of tabs open when I close/reopen Chrome. After doing the @jafin hack, reopening Chrome after a shutdown brings back the same behavior of lost URLs as before. I had to go in and re toggle and then go into history and reopen the group of tabs (because when you re toggle AFTER a shut down, the tabs disappear in that window).
> 
> Does anyone have a line to the developer? We really need to get a fix on this asap (please).

Also, even when I do this, some of my suspended tabs disappear when after doing the "fix". I've been using session buddy to keep track of all my tabs and doing a full restore from there after turning url access on.

**Comment by bobsage123** [comment]
Has anyone tried yet on new chrome build 91.0.4472.102 that came out today? Don't feel like dling it and having to fix all my tabs if it doesnt fix it.

**Comment by bobsage123** [comment]
Chrome team is aware of issue https://bugs.chromium.org/p/chromium/issues/detail?id=1216788

**Comment by q00u** [comment]
It's still not working in 91.0.4472.101

**Comment by Gyumaou** [comment]
Yeah apparently the fix was merged into 4470 release but not working here either.

**Comment by peterrakmanyi** [comment]
Reading the mailing list on chromium issue [1216788](https://bugs.chromium.org/p/chromium/issues/detail?id=1216788), it appears these are the most relevant bits from the opening comment:
```
"Steps to reproduce the problem:
uBlock Origin ("uBO") and probably all extensions making use of chrome.tabs.executeScript() are broken
by extensions which make use of the declarativeContent() API (examples: ViolentMonkey, TamperMonkey)."
```
A solution from [comment 16](https://bugs.chromium.org/p/chromium/issues/detail?id=1216788#c16)
```
FWIW: In Tampermonkey you can work around the problem by setting "Injection Mode" to "Instant"
(config mode needs to be set to "Advanced" in order to see this setting), since then no
declarativeContent rule is used anymore.
```

So if you use another extension that calls the declarativeContent() API, try setting them to not use it.

### The solution that worked for me in TamperMonkey:
```
Dashboard -> Settings ->
    1. General -> Config Mode -> set to 'Advanced'
    2. Experimental -> Inject Mode -> set to 'Instant'
```

**Comment by nihaals** [comment]
The [fix](https://github.com/chromium/chromium/commit/1210d51d3ea3dee472310a590d8af454896d0f62) is part of `91.0.4472.106` and Chrome stable has [bumped its version](https://chromereleases.googleblog.com/2021/06/stable-channel-update-for-desktop_14.html) to include the fix, so you should see a Chrome update soon:tm: as it rolls out

**Comment by Gyumaou** [comment]
Fixed now in new chrome update.

**Comment by bobsage123** [comment]
> The [fix](https://github.com/chromium/chromium/commit/1210d51d3ea3dee472310a590d8af454896d0f62) is part of `91.0.4472.106` and Chrome stable has [bumped its version](https://chromereleases.googleblog.com/2021/06/stable-channel-update-for-desktop_14.html) to include the fix, so you should see a Chrome update soon™️ as it rolls out

Do we need to keep the "allow url access" permission on for this to work still? I'm still having issues loading all my suspended tabs. After the update.

**Comment by bobsage123** [comment]
I'm not sure if something is still buggy going on in the latest version. YouTube videos are now choppy again. Which were only fixed last time after I did the "URL access fix".
