### ISSUE TITLE
Suspended tabs name with 3 dots and white page.

### ISSUE THREAD

**Issue by PatrickL546** [gioxx/MarvellousSuspender#161]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: v7.1.6.2
 * Browser name & version: Google Chrome 99.0.4844.51
 * Operating system & version: Win 10 21H2

Suspended tabs turns to default icon with 3 dots and white background until I click on it and it loads the proper suspended tab. Even after it loads if you click away and go back to the tab, it turns white again. Seems to be from the new chrome update.

What happens when it gets suspended
![image](https://github.com/gioxx/MarvellousSuspender/assets/75874561/ebf185b2-29fc-4744-9ffe-82638270a7c5)

What it should look like
![image](https://github.com/gioxx/MarvellousSuspender/assets/75874561/d6ea9499-8263-4018-bf8f-2940b4b768f2)

**Comment by s-p-l-o-d-e** [comment]
Yeah I've been having the same issue.
Tabs only fully get suspended when you navigate to a different tab and then back to the suspended one.
When clicked on, recently fully suspended tabs also go white with the three dots again for a few seconds before showing the suspended screen.

I've tried other variants of the Great/Marvellous Suspender (7.1.6, no-track, this one, not the "official" tracked one though) and they all have this issue now for some reason.
Maybe it has to do with base chromium code?

Running Brave Browser [Version 1.36.109 Chromium: 99.0.4844.51]
Issue happens on both MacOS 12.2.1 and Windows 10

Edit: Just testing it out, it seems like the extension (and variants) are taking longer to cache the data from the page or something similar and that clicking back and forth between tabs and waiting a few seconds eventually lets it do that.

**Comment by s-p-l-o-d-e** [comment]
Okay, I seem to have fixed it, for some reason

Poking around the Chrome (or in my case, Brave) flags, I found this new flag called "New Tab Page Demo Branded Wallpaper"
Disabling this, causes Marvellous Suspender to function properly.

<img width="733" alt="Screen Shot 2022-03-04 at 9 09 39 AM" src="https://user-images.githubusercontent.com/92898262/156778440-744874c2-5393-4782-914a-59883aacc00c.png">

This is probably for the best since who the hell wants to see more branding in their browsers?

Edit: This seems to be a Brave specific flag only, rather than a Chrome or Chromium one.

**Comment by rex** [comment]
@s-p-l-o-d-e I am on Chrome `99.0.4844.51` and I do not see that flag in the list. Perhaps that is a non-standard flag related to Brave? Or you might be on a beta channel?

This issue is really frustrating, and causes huge user experience issues. 

I've gone through the debugger tree and identified the problem, hopefully y'all can resolve this and push an update soon? 

The issue is in the `gsUtils.js` file in the `isSpecialTab` function. You are retrieving the URL of the tab with the following:
```js
const url = tab.url || tab.pendingUrl;
```
The problem is, the `tab` object does not always have the `url`, `pendingUrl`, or even `title` properties (which is extremely stupid on Chrome's part, and seems like a full-on chrome bug), so `url` becomes `undefined`. This becomes a problem in the next lines:
```js
if {
    url.indexOf('about') === 0 ||
    url.indexOf('chrome') === 0
```
Since `url` is `undefined`, there is no `indexOf` method to call, thus throwing an uncaught exception.

Simply adding a sanity check to the top of this function would bypass the issue and resolve the problem:

```js
if (typeof url == 'undefined') {
    return false;
}
```

**Comment by s-p-l-o-d-e** [comment]
> @s-p-l-o-d-e I am on Chrome `99.0.4844.51` and I do not see that flag in the list. Perhaps that is a non-standard flag related to Brave? Or you might be on a beta channel?

Interesting, yeah it seems that is a Brave specific flag, rather than a standard Chrome/Chromium one.
Sorry about that.

Your sanity check is interesting, does it work if it's added to gsUtils.js file and loaded as an unpacked extension?

**Comment by rex** [comment]
All good @s-p-l-o-d-e! 🤠 

I disabled the extension and re-installed as an unpacked extension, made the modification to `gsUtils.js` I recommended above, reloaded the extension, and all the errors immediately stopped - the extension now behaves normally again. Which is a tremendous relief since it was getting painful there for a bit. 

**Edit:** 

Specifically, I made the following exact change:

```js
  isSpecialTab: function(tab) {
    const url = tab.url || tab.pendingUrl;
    if (!tab || typeof tab == "undefined") {
      return false;
    }
    if (gsUtils.isSuspendedTab(tab, true)) {
      return false;
    }
    // Careful, suspended urls start with "chrome-extension://"
```

**Comment by s-p-l-o-d-e** [comment]
Nice, that's awesome, good work!
Hopefully they update the extension with that addition or something similar.

**Comment by rex** [comment]
Thanks! Agreed. This definitely appears to be a Chrome issue caused by a _very_ recent change. I'm sure we're not the only ones seeing this. Hopefully @gioxx and crew can get the update made and pushed soon.

**Comment by n3m0-22** [comment]
I can confirm the brave specific flag "New Tab Page Demo Branded Wallpaper" being disabled fixes it at least in brave browser.
(Correction) It only works till the browser is restarted again.

**Comment by DaveKap** [comment]
The last time this extension was updated was almost a year ago, so we're going to need someone to fork a fixed version or a new workaround for Chrome users. I wouldn't hold by breath for gioxx pushing an update.

**Comment by matznerd** [comment]
Thanks @rex and @s-p-l-o-d-e, at the change to the gsUtils.js file did help when I uploaded it, but upon restart of the browser, the problem seems to have returned. Do we have a permanent solution to this or is this user error and should I try again? 

Also, is @gioxx, who we are very thankful for doing this fork, still actively making code updates?

> ```js
>   isSpecialTab: function(tab) {
>     const url = tab.url || tab.pendingUrl;
>     if (!tab || typeof tab == "undefined") {
>       return false;
>     }
>     if (gsUtils.isSuspendedTab(tab, true)) {
>       return false;
>     }
>     // Careful, suspended urls start with "chrome-extension://"
> ```

**Comment by rex** [comment]
@matznerd Weird, I've had no more issues despite restarting my browser several times. You removed the chrome-webstore-installed extension and loaded the source as an unpacked extension right?

**Comment by matznerd** [comment]
Yeah, what is strange is that it stopped working that time, but then upon reset again today, it is back to working. Thank you for checking in! I'm not sure if it was because the browser auto updated or something. Right now I am on 'Version 99.0.4844.51 (Official Build) (64-bit)" with your fix and it is working

I also emailed @gioxx to see if he was planning to fix it, or if someone should fork it, or if he would accept a merge from a forked version, so that we don't have to come up with some other synonymous for a synonym for a fork name... Though, how about the stupendous suspender, which is almost a tongue twister lol? Or maybe we could go a more modest route and called it "The Pretty Good, But Not Often Updated Suspender"?

https://thesaurus.yourdictionary.com/marvelous

**Comment by gioxx** [comment]
Hi everyone and sorry for the delay.
I have been silently following the discussion and want to thank @rex very much for providing the solution to the problem. Unfortunately - as I've said several times - I'm out of developers willing to contribute to TMS development but I've scheduled a new coding session for Sunday (with @napolux and @sherkot), during which we'll include @rex's fix and also try to integrate Chrome's tab group saving. If we succeed in these two important actions, then it will certainly be possible to release the new version of TMS on the Google store.

Once again I want to renew my invitation to come forward in case you want to contribute to the development of the extension. I'm a system administrator with poor development skills, I certainly need capable people to carry on this project that I absolutely don't want to drop.

Thanks.

**Comment by CollinChaffin** [comment]
I also want to thank @rex for posting the fix - he beat me to it. Honestly, I've just been using for the last couple years my own unpacked version of the original TGS, after I myself caught and neutered the tracking code and decided to use my own build. Rex is correct, and this I can confirm this IS due to a recent Chromium code change. If you guys can get this and the tab group saving rolled in, now that I know about this fork I'll also contribute here if I can.

For the record, I've been using TGS since day 1, and NEVER relied on it for it's session management, simply because I already was using an extension that did it better - and session management being the ONLY thing it does - I take K.I.S.S. - (keep it simple, stupid) approach when possible. Plus, this other extension is simple yet powerful, and despite not being open-source, admittedly I've (ahem) torn it apart so I'm convinced it's safe. Now, I will say it hasn't had a (meaningful) update in a LONG time, but the beauty is, it doesn't really need one IMO as far as it's core functionality.  

It's Session Buddy: https://chrome.google.com/webstore/detail/session-buddy/edacconmaakjimmfgnblocblbcdcpbko

Now, they have a forum, and I'm not affiliated in any way, just a power-user but...once you understand where the sqlite db it uses is stored, I personally not only back it up, but love that I can open the db and run stats and work with/alter the data in sqlbrowser. Just speaking for myself, but I've got YEARS and TENS OF THOUSANDS of auto-saved tab states, and since in addition to manual saves, it auto-saves so there's never been a situation where I've had a browser crash etc. and lost my state. I can do an INSTANT search of those tens of thousands, click and restore a single window, or tab. If you're like me and with the help of TGS/TMS, have six windows and 284 tabs open (right now), with most suspended, and in seconds use SB to jump to the suspended tab I want - I just haven't found another solution that comes close. It is lacking some things that if it were open-source I would have added myself, like dark mode - but I've come up with some pretty cool hacks that if anyone is interested I'll be happy to share.

The reason I mention this, is that since there are FAR more powerful session management extensions, and obviously a shortage of developers maintaining TGS/TMS, I know I'd not only be ok, but would actually LIKE to see TGS/TMS just remove the session management all together (to save performance overhead), and focus ONLY on what it does best - tab suspension. If it ever went that route, the small # of devs could focus on keeping it the #1 tab suspension extension and not worry about session mgmt that frankly unless something radically changes, will never come close to even what Session Buddy does. Just a thought.

**Comment by ogrotten** [comment]
One of the most productive threads I've seen on github in a while. Thank you all for your work and diligence.

So for us regular users, what's the fix at this point?

**Comment by napolux** [comment]
> One of the most productive threads I've seen on github in a while. Thank you all for your work and diligence.
> 
> So for us regular users, what's the fix at this point?

Wait for a release

**Comment by rex** [comment]
@CollinChaffin I gotta tell you - as a long-time user of TGS and now TMS, I would _love_ to see the session management stuff ripped out. As you point out, there are far more powerful session management extensions out there, and it would significantly reduce the code overhead for @gioxx and crew to not have to maintain it. 
 
With regard to the original issue, I did want to add one additional fix since I've been having the same issue on incognito tabs:

In addition to the above code changes in `js/gsUtils.js` I modified the `isFileTab` method in the same way, as follows:

```js
isFileTab: function(tab) {
  if (!tab || typeof tab == "undefined") {
    return false;
  }
  const url = tab.url || tab.pendingUrl;
```

After making this additional change I have had no other issues. 

**Ninja edit:** I forgot to thank everyone for the kind shout-outs. I'm glad I was able to help other people resolve their issue, and especially to help @gioxx and team.

**Comment by Technetium1** [comment]
I personally like the session management aspect, though I will admit I also use Session Buddy as a backup. How significant of a change would you suppose removal would bring? Has that been tested in some capacity or is it an assumption? @CollinChaffin

**Comment by ogrotten** [comment]
@napolux That's what I was afraid of.

As far as session management, I use Session Buddy and wasn't aware that this even had some kind of session management.

**Comment by ossilator** [comment]
regarding session management, see also https://github.com/greatsuspender/thegreatsuspender/issues/1251

**Comment by marceloavf** [comment]
I'm having this problem on Edge, seems like the Performance mode cleans the cache of it.

**Comment by CollinChaffin** [comment]
@Technetium1 sorry for the delay in replying!  Looking at the code, I think in the big picture, it's frankly a pretty high percentage of code being maintained for what (and please I mean no offense to anyone) fairly subpar session management features. If it was the only/best option out there, then I wouldn't suggest it - but I don't think anyone (who's actually tested the other available session mgmt extensions) would argue it's anywhere near the best available.

Which leaves two possible goals - either put forth SIGNIFICANTLY more effort than has previously been put forth to make it the best.....or abandon it entirely.  Given I have actually tested (and use) one of the other options and can go down the list of just how much more feature-rich that other option is, I was simply putting out there my vote that at the very least, TGS/TMS users partake in a controlled simultaneous usage, and if more and more find themselves going the route I did YEARS ago, and completely abandoning TGS/TMS session mgmt (and voicing it here), then the DEV team would feel much more comfortable sun-setting the session mgmt and making TMS far more lean, and with those (significant) extra DEV cycles no longer being wasted on S-mgmt, perhaps bring forth new and exciting (and long-time requested) features such as LIVE sorting/reordering/window-moving/etc. of suspended tabs which does NOT require any session mgmt storage making it far easier - because in my case Session Buddy would simply store those tab manipulations automatically.

And @rex - NICE! I totally missed that, albeit I don't do much w/incognito TMS - but you are absolutely correct in that your fix needs to be incorporated along with your original post.  I've already implemented in my local build and can confirm it works beautifully.  Thanks!

EDIT: @rex technically, and you can test this as well....the best way to do it might be to take:

```
if (!tab || typeof tab == "undefined") {
    return false;
  }
```
and define it as a IsUndefined function, and make it the first line in EVERY function that accepts `(tab)` as input param. That way, the undefined test is performed at every single tab manipulation, no matter what the test. I'm running that way now, and have not experienced any negative effects.

**Comment by Masamune3210** [comment]
The only parts of the extension I use is the automatic suspending of tabs, and the whitelist for individual domains to never get suspended

**Comment by shanness** [comment]
This also seems to be breaking reloading the page.  It no longer unsuspends it.

Clicking does (after leaving and coming back to the page which updates it from ... and white to normal on latest chrome).

This is breaking my automations (pushing reload requests into suspended pages).

**Comment by PatrickL546** [comment]
In regards to session management in TGS/TMS, I have never used built-in session management because of how clunky it feels. In terms of UX, Session Buddy has it beat with how few clicks it takes to use. Going into the TGS/TMS settings and session management is slow when 1 click is all I need in Session Buddy. I have not used other session management other than Session Buddy but it gets the job done.

On the other hand, I guess the built-in session management made it easier for people to recover suspended tabs when Chrome Web Store shuts down TGS.

**Comment by ossilator** [comment]
the session management is merely a workaround for TGS nuking all suspended tabs during upgrades. in think that has been fixed (the upgrade is now performed only during chrome startup, before the session gets restored), thus making it redundant. @deanoemcke still had some reservations against simply removing it, but the only thing i remember is that i found the reasoning somewhat inconclusive.

**Comment by Technetium1** [comment]
Looking forward to seeing any input from Dean, as he would know the surrounding context for why the code was not removed.

@CollinChaffin The logic there is sound, you've got me on board with removal. I strongly agree that an `IsUndefined` function would be a good idea. Thanks for contributing!

**Comment by HananArgov** [comment]
Hi all,
I've been reading this thread for a while, especially since i've experienced the same issues.
i've noticed something in the last chrome update (which I did a few moments ago): the issue seems to be fixed by chrome.
I do support though that the fix that you've made should be entered


and in general, thank you for this :)

**Comment by pannal** [comment]
> Hi all, I've been reading this thread for a while, especially since i've experienced the same issues. i've noticed something in the last chrome update (which I did a few moments ago): the issue seems to be fixed by chrome. I do support though that the fix that you've made should be entered
> 
> and in general, thank you for this :)

Hmm not for me. I'm on Chrome 99.0.4844.84 and the issue is still there.

**Comment by TonyYangTW** [comment]
> Hmm not for me. I'm on Chrome 99.0.4844.84 and the issue is still there.

Try updating to Chrome 100.0.4896.60. That might work!

**Comment by Technetium1** [comment]
If they caused a regression and then fixed it _after_ a release was finalized, it will probably be a while before it gets to every release channel.

**Comment by nihaals** [comment]
Chrome M100 was released as stable on 2022-03-29, nice timing
Although I can still reproduce the issue on 100.0.4896.60

**Comment by PatrickL546** [comment]
Can confirm on my end. Version 100.0.4896.60 (Official Build) (64-bit) problem still persists.

**Comment by marceloformentao-hotmart** [comment]
The fix will not be released?

**Comment by PatrickL546** [comment]
> The fix will not be released?

You can download rex's fork with the fix (https://github.com/rex/MarvellousSuspender) and load as unpacked the src to chrome.

**Comment by briantully** [comment]
> > The fix will not be released?
> 
> You can download rex's fork with the fix ([rex/MarvellousSuspender](https://github.com/rex/MarvellousSuspender)) and load as unpacked the src to chrome.

Can confirm that the fork and fix by @rex works like a charm. Thanks @rex! 🍻

Any idea where the future source of truth will be for this essential extension? Are there plans to merge rex's work into this repo or is rex'a fork now the de facto source?

**Comment by gioxx** [comment]
@briantully soon we merge @rex code into this repo and release a new version of TMS on Chrome Store. I'm just waiting a revision from @napolux to proceed.

**Comment by briantully** [comment]
> @briantully soon we merge @rex code into this repo and release a new version of TMS on Chrome Store. I'm just waiting a revision from @napolux to proceed.

Awesome. Thanks for all you do, and for everyone's contributions in keeping this extension alive. I don't know what I'd do without it! 😄

**Comment by Laz2516** [comment]
Tell me which file to download? I probably downloaded the wrong file. After decompressing and installing in debugger mode, there was no change in the page icons. Icons still change to the application icon after you unload the page from memory.

**Comment by PatrickL546** [comment]
> Tell me which file to download? I probably downloaded the wrong file. After decompressing and installing in debugger mode, there was no change in the page icons. Icons still change to the application icon after you unload the page from memory.

First uninstall the extention
Then download ZIP (https://github.com/rex/MarvellousSuspender) then extract to somewhere
![image](https://user-images.githubusercontent.com/75874561/161377725-7c10673b-aede-4fd2-a961-5c83890d03dd.png)

Load as unpacked once you enabled dev mode
![image](https://user-images.githubusercontent.com/75874561/161377808-686a61bf-67c1-4596-921c-6b9e348d5865.png)

Select this folder to install it
![image](https://user-images.githubusercontent.com/75874561/161377766-46d55e5e-0a08-4845-9b29-0eb7c67a79d3.png)

**Comment by Laz2516** [comment]
Restored all bookmarks. Set the tab pause mode to Never. Deleted the extension. Downloaded the file. 
https://github.com/rex/MarvellousSuspender/archive/refs/heads/master.zip
Unarchived. Set the src folder in debug mode.
The application showed the start page. It was established correctly.
Set the pause mode to "15 minutes."
After the tabs are suspended, all icons became the same   - they are all the same and have a program icon, not a page....... ((((

**Comment by Laz2516** [comment]
I don't understand anything. Why not? (
The latest version of Chrome is updated by the machine.

**Comment by Laz2516** [comment]
Found a reason. You need to turn the extension off and on.

**Comment by Laz2516** [comment]
P.S.    unfortunately this method does not work to the end. After rebooting the extension, the icons are restored with thumbnails of their pages. But after entering the page and then unloading the page from memory with this extension, the page icon becomes the extension icon again..... ((((

**Comment by ptxmac** [comment]
I still see this issue with v7.1.6.2 on chrome 101.0.4951.15

**Comment by nihaals** [comment]
I can still reproduce the issue on 8bda8531a386ad6514c2df9d0890be03ede89d54 and 100.0.4896.75

**Comment by berkshireasia** [comment]
I still see this issue with v7.1.6.3 on chrome 100.0.4896.60

**Comment by berkshireasia** [comment]
I still see this issue with v7.1.6.3 on chrome 100.0.4896.75

**Comment by gioxx** [comment]
@nihaals @berkshireasia are you continuing to use the version installed from the Chrome Store or the one on GitHub manually loaded in Chrome?

**Comment by nihaals** [comment]
> are you continuing to use the version installed from the Chrome Store or the one on GitHub manually loaded in Chrome?

I am using a local clone and have loaded it as unpacked.

**Comment by PatrickL546** [comment]
Seems like Version Google Chrome 100.0.4896.75 with v7.1.6.3 is kinda still bugged. I've tried it and the 3 dots title and white page only occur when suspending it the first time. Here's what I did.

Open a site and suspend it. It turns to the bugged page.
Go to another tab and comes back, after a sec it loads the page correctly and it seems after this, it's fixed until it's unpaused then paused again.

This is only an observation and  I haven't looked deep into it.

**Comment by Ocel8** [comment]
I use chrome Dev. and I had this problem but it seems to be solved (it disappeard a couple of update ago).
At the same time now everytime you unsuspend a tab it reloads two times with a couple of seconds between the two, and it's super annoing

**Comment by berkshireasia** [comment]
> @nihaals @berkshireasia are you continuing to use the version installed from the Chrome Store or the one on GitHub manually loaded in Chrome?
@gioxx 
Similar to @nihaals I also downloaded version 7.1.6.3 manually loaded. In any case, neither this one nor the one on Chrome Store fix the problem...

**Comment by briantully** [comment]
Should this issue be reopened? Seems to be occurring again with Chrome 100.0.4896.75 and 7.1.6.3 (master branch) from this repo loaded unpacked.

I'm seeing suspended tabs change icon to the Marvellous Suspender icon with 3 dots, then viewing the tab it's initially white screen and then changes to  display "Undefined".

The error showing within the extension console is:

`Error handling response: TypeError: Cannot read properties of undefined (reading 'pop')`

So it seems it's losing track of the suspended tab URLs array/session?

**Comment by tomasz1986** [comment]
> Should this issue be reopened?

I'd also like to ask to re-open the issue. It doesn't seem to be fixed, or at least not completely fixed. I've compiled the extension from source with all the newest patches, and I still keep getting these errors with some of the suspended tabs.

This is how such a problematic tab looks like.

1. Before clicking on it:
   ![image](https://user-images.githubusercontent.com/5626656/162559265-e6789df3-4c1a-4445-b969-1cddc58e27f1.png)

2. After clicking on it:
  ![image](https://user-images.githubusercontent.com/5626656/162559271-cefdc2be-a405-4a61-8c45-39dbe3a8e69c.png)
  ![image](https://user-images.githubusercontent.com/5626656/162559277-88a94a47-2ada-42b3-9b68-10ab9d7e0126.png)

Fortunately, it is still possible to display the suspended site by trying to navigate back.

**Comment by Kolossi** [comment]
+1 for reopening I also have the issue described by @tomasz1986 

Also, it's fine having a fix in source, but there's no release on here let alone it being an update on the chrome store.

@gioxx I do realise software issues are normally closed when the fix is in source, but in this case where it's not some kind of side functionally but the core purpose of the app doesn't work, istm it would be best to leave this open until the fix is published and confirmed there are no obvious problem scenarios.

Not meaning to rant - the software is great, the fact it was picked up from the code base which had been malwared is great, it wasn't this code's fault the bug appeared it was google what broke it. Just really like it and want it back - thanks for your efforts @gioxx and all those who found and fixed 👍🏻

**Comment by napolux** [comment]
> I still keep getting these errors with some of the suspended tabs.

Hey thanks for this. Can you answer some questions in order to help debug the issue?

* Some or all your tabs? 
* Does it happens even on freshly suspended tabs or old ones?
* Any other issue?

**Comment by tomasz1986** [comment]
> * Some or all your tabs?

Only some, and it doesn't seem consistent, e.g. I opened a few tabs with the same website, and only a few of them ended up in this state. Not sure if this will be of any help, but at this very moment I'm experiencing the problem with the following URs.

https://stdict.korean.go.kr/search/searchView.do?word_no=146232&searchKeywordTo=3#
https://www.theverge.com/2017/9/28/16378364/cuphead-art-design-1930s-animation

For the record, it appears to only happen after a tab has been suspended automatically (which is set to 1 hour in my case). When suspending it manually, everything seems to work fine.

> * Does it happens even on freshly suspended tabs or old ones?

It happens on freshly suspended ones, unfortunately.

**Comment by ptxmac** [comment]
> For the record, it appears to only happen after a tab has been suspended automatically (which is set to 1 hour in my case). When suspending it manually, everything seems to work fine.

I just had the issue with a manually suspended tab, so I don't think manual vs auto has any impact. Seems very random to me

**Comment by xodotLBO** [comment]
Even after fix its happening again after updating chrome

**Comment by ogrotten** [comment]
I have 2 systems using this.

Basement system is 
* Win10
* Chrome Version 100.0.4896.75 (Official Build) (64-bit)

Work system is 
* Win 11
* Chrome same version

Basement system works as expected. It has never had a problem. 

Work system has the problem, since before my first post in this thread on 15-Mar-2022.

**Comment by jenci8888** [comment]
~~I'm having a same problem too.~~

EDIT: Okay, it's fixed after chrome updated to 100.0.4896.88, as I tested the oldest 7.1.6 version (github forked) and ran without issues. (I don't know what Chrome was in issue, I'll keep monitoring in future)

I've used:
- Windows 10 21H2 (build number: 19044.1620)
-  Chrome Version 100.0.4896.88 (Official Build) (64-bit)

**Comment by NoReasonKen** [comment]
After an update of chrome, from 100.0.4896.75 to 100.0.4896.88, it works perfectly now

I'm on
- Mac 12.3.1
- Chrome 100.0.4896.88 64bit
- MarvellousSuspender 7.1.6.2 (Downloaded from chrome web store long time ago)

**Comment by gioxx** [comment]
Ok, thanks @NoReasonKen.
@ogrotten @xodotLBO @ptxmac @tomasz1986 @Kolossi and others with the problem, could you please test again TMS (GitHub version) with an updated Chrome? I want to know if we can release a new TMS version for all our users.
Please leave then a feedback at the end of the test to understand if everything works for you too.
Thanks!

**Comment by ptxmac** [comment]
>could you please test again TMS (GitHub version) with an updated Chrome?

Will do - did you mean build from source, or is there an existing release we can just download?

**Comment by gioxx** [comment]
> 
> Will do - did you mean build from source, or is there an existing release we can just download?

You can build or just download a copy of the repository and load src folder in Chrome (unpacked extension).

**Comment by ptxmac** [comment]
Cool, installed - it usually takes some time before the issue starts appearing, so I'll add a comment if I see it again

**Comment by gioxx** [comment]
Thanks!

**Comment by ptxmac** [comment]
Just confirmed - this happened again using the version on master

**Comment by gioxx** [comment]
> Just confirmed - this happened again using the version on master

Is Chrome updated? Can you check (and write here) the version in use?

**Comment by ptxmac** [comment]
More than just updated, I'm on the beta channel 😄 

`Version 101.0.4951.26 (Official Build) beta (arm64)`

**Comment by gioxx** [comment]
Got it, this is so strange, because the problem seems to be solved on the Current Channel (100.0.4896.88)! 🤔😢

**Comment by aarondchu** [comment]
Im on `Microsoft Edge Version 100.0.1185.36 (Official build) (64-bit)` and this issue is fixed

**Comment by jenci8888** [comment]
> ~I'm having a same problem too.~
> 
> EDIT: Okay, it's fixed after chrome updated to 100.0.4896.88, as I tested the oldest 7.1.6 version (github forked) and ran without issues. (I don't know what Chrome was in issue, I'll keep monitoring in future)
> 
> I've used:
> 
> * Windows 10 21H2 (build number: 19044.1620)
> * Chrome Version 100.0.4896.88 (Official Build) (64-bit)

Restarted PC and restarted chrome, encounter the same issue as before, just nothing new. (still unresolved.)
When browser updates, and it would be resolved the issue until restart chrome & restart PC.

**Comment by nihaals** [comment]
I can also still reproduce the issue.

- Google Chrome 100.0.4896.88 (arm64)
- macOS 12.3.1

**Comment by NoReasonKen** [comment]
@jenci8888 @nihaals 

Humm, But the extension works perfectly even if I restart my computer
I have tried to switch the option of extension which will use build-in system memory release function of chrome, and it is good in both conditions

**Comment by pressRtowin** [comment]
Very oddly, when I updated chrome to version 100, it stopped doing this. Stayed that way for a couple weeks, then started doing it again within the last 24 hours. I intentionally didn't install the current update that it's prompting me to restart chrome for (my system, and chrome, stays on for long periods of time).

**Comment by ogrotten** [comment]
I kept an eye out during the day on my work machine. I will do so again tomorrow and update.

**Comment by a1termoon** [comment]
For me all ok. You use this? 
![image](https://user-images.githubusercontent.com/58614810/163545703-a6e3e24d-95da-485b-8648-27f1896d1c5f.png)

**Comment by PatrickL546** [comment]
> For me all ok. You use this? ![image](https://user-images.githubusercontent.com/58614810/163545703-a6e3e24d-95da-485b-8648-27f1896d1c5f.png)

It's a feature from when people are using the original TGS and chrome deletes the extention so people can't unsuspend the tabs. It takes over those tabs and enable people to unsuspend it.

Not really used nowdays. You can keep it on, doesn't really affect you.

**Comment by ogrotten** [comment]
> Ok, thanks @NoReasonKen. @ogrotten @xodotLBO @ptxmac @tomasz1986 @Kolossi and others with the problem, could you please test again TMS (GitHub version) with an updated Chrome? I want to know if we can release a new TMS version for all our users. Please leave then a feedback at the end of the test to understand if everything works for you too. Thanks!

I did not see a problem today. At least by appearance it seems to be working again.

Thanks for giving a crap.

**Comment by hargobind** [comment]
Reporting that I experienced this issue with the latest `master` branch (7.1.6.3), unpacked, on Chrome 100.0.4896.127 on Windows 10 Pro.

Here's the debug log from the `background page`
```
Error in event handler: TypeError: Cannot read properties of undefined (reading 'indexOf')
    at Object.testForMatch (chrome-extension://gfkmanbeiohkbjdkpnhfocbcjdkaoijm/js/gsUtils.js:357:19)
    at Object.<anonymous> (chrome-extension://gfkmanbeiohkbjdkpnhfocbcjdkaoijm/js/gsUtils.js:311:22)
    at Array.some (<anonymous>)
    at Object.checkSpecificWhiteList (chrome-extension://gfkmanbeiohkbjdkpnhfocbcjdkaoijm/js/gsUtils.js:310:34)
    at Object.checkWhiteList (chrome-extension://gfkmanbeiohkbjdkpnhfocbcjdkaoijm/js/gsUtils.js:298:20)
    at calculateTabStatus (chrome-extension://gfkmanbeiohkbjdkpnhfocbcjdkaoijm/js/background.js:1302:17)
    at handleUnsuspendedTabStateChanged (chrome-extension://gfkmanbeiohkbjdkpnhfocbcjdkaoijm/js/background.js:777:7)
    at chrome-extension://gfkmanbeiohkbjdkpnhfocbcjdkaoijm/js/background.js:1725:9
```

I've traced the error back to `calculateTabStatus()` in background.js. Through debugging the value of `tab`, I found that sometimes `tab.url` is empty. I tested this by manually suspending a tab using a keyboard shortcut.

Ack! During my testing/debugging, I was able to reproduce this perfectly. But then I restarted my browser and now I can't reproduce the issue anymore. So I can't tell you why `tab.url` was empty earlier, but now it always has the URL value. If I encounter this again, I'll see if I can debug this further.

**Comment by nihaals** [comment]
For future reference, HEAD for https://github.com/gioxx/MarvellousSuspender/issues/161#issuecomment-1100843246 is 8bda8531a386ad6514c2df9d0890be03ede89d54

**Comment by Winsane** [comment]
I was poking around a bit, and found a fix. It feels like a bit of a spaghetti band-aid fix though, but I haven't had time to investigate further yet.
I edited this function:
https://github.com/gioxx/MarvellousSuspender/blob/8bda8531a386ad6514c2df9d0890be03ede89d54/src/js/gsMessages.js#L104-L126
Like this:
```JS
  sendMessageToTab: function(tabId, message, severity, callback) {
    if (!tabId) {
      if (callback) callback('tabId not specified');
      return;
    }
    var responseHandler = function(response) {
      gsUtils.log(tabId, 'response from tab', response);
      if (chrome.runtime.lastError) {
        if (callback) {
          if (severity == "error"){
            chrome.tabs.get(tabId,gsTabCheckManager.queueTabCheck);
          }
          callback(chrome.runtime.lastError);
        }
      } else {
        if (callback) callback(null, response);
      }
    };
    message.tabId = tabId;
    try {
      gsUtils.log(tabId, 'send message to tab', message);
      chrome.tabs.sendMessage(tabId, message, { frameId: 0 }, responseHandler);
    } catch (e) {
      // gsUtils.error(tabId, e);
      chrome.tabs.sendMessage(tabId, message, responseHandler);
    }
  },
```

So basically, if severity == "error", send the tab to queueTabCheck. Feels like we could easily end up in some sort of infinite loop with this, but I've been using the fix for a couple of weeks now with almost always 30+ tabs with no issues.

**Comment by hargobind** [comment]
Thankfully the bug returned, so I was able to continue testing. I ran tests by suspending an individual tab via all the normal methods (extension icon, right-click, keyboard shortcut), and suspending all other tabs in the window via the same procedures.

I've traced the issue back to `chrome.tabs.onUpdated.addListener(function(tabId, changeInfo, tab) {});` in `background.js`.

The issue here is that `tab` does not contain a full copy of the tab. Specifically, `tab.url` is missing. I don't know the code of this extension well enough to understand how TMS suspends tabs, but I imagine the "tab suspend" code might be the culprit.

As a workaround, I've attached a patch to deal with the missing `tab.url`. It checks if `tab.url` is undefined then call `chrome.tabs.get(tabId)`. Then proceed handling the tab update. Since `tab.url` may still exist in some scenarios, I have moved the code that was in `onUpdated.addListener()` to its own handler function.

**Patch file:** [tms-161-onUpdated-fix.patch.txt](https://github.com/gioxx/MarvellousSuspender/files/8517237/tms-161-onUpdated-fix.patch.txt)
See #179 for the PR.

This might be the best fix going forward. However, I still wonder how `tab.url` is missing, and I'm guessing it has to do with how TMS suspends tabs. If that can be tracked down and fixed, then this workaround won't be necessary.

I also don't know the TMS code well enough to know whether my approach or @Winsane 's approach is better. But after applying their fix, I was still seeing errors in the DevTools console related to a missing `tab.url`. To fix this, it's still necessary to modify `calculateTabStatus()` and change:
`    if (gsUtils.checkWhiteList(tab.url)) {`
to:
`    if (typeof tab.url !== 'undefined' && gsUtils.checkWhiteList(tab.url)) {`

**Comment by pannal** [comment]
> 

Please fork instead of posting patches, so more people can test your changes more easily! Thanks!

**Comment by hargobind** [comment]
@pannal I don't have a lot of experience with GitHub. Please send a link of a guide on what the etiquette is for contributing forks/patches to an issue.

**Comment by pannal** [comment]
> @pannal I don't have a lot of experience with GitHub. Please send a link of a guide on what the etiquette is for contributing forks/patches to an issue.

Hmm, normally basically fork (there's a button on top of this; top-right) and check out/clone your fork locally, apply your changes, push your fork, then create a pull request on github (it even appears automatically after you've pushed). It's fairly straight forward.

Edit: The only thing you need is a Github account and a couple of clicks.
Edit 2: You might want to change `typeof tab.url != 'undefined'` to `typeof tab.url !== 'undefined'` :)

**Comment by sicklittlemonkey** [comment]
> @pannal I don't have a lot of experience with GitHub. Please send a link of a guide on what the etiquette is for contributing forks/patches to an issue.

GitHub has a guide for this and other topics:
https://docs.github.com/en/get-started/quickstart/contributing-to-projects

Also, if you're on Windows or macOS there is a desktop app that makes things easy:
https://desktop.github.com/

**Comment by xodotLBO** [comment]
So is there a fix that's out/out for this or what's happening? I'm still getting annoyed by this but have to use the extension.

**Comment by nihaals** [comment]
#179

**Comment by Winsane** [comment]
> I also don't know the TMS code well enough to know whether my approach or @Winsane 's approach is better.

@hargobind Your approach looks more sane! But I'm also still curious why we get the empty tab.url in the first place, because fixing that would be more satisfying and efficient than having code babysitting to correct the actual bad code.

**Comment by hargobind** [comment]
> 
> @hargobind Your approach looks more sane! But I'm also still curious why we get the empty tab.url in the first place, because fixing that would be more satisfying and efficient than having code babysitting to correct the actual bad code.

Agreed! I'm also curious why there seem to be around 10 calls to `chrome.tabs.onUpdated()` every time a tab is suspended.

I only tracked the issue as far up the execution tree as I could. If someone wants to point me in the direction of the `SuspendTab()` code, I'm happy to look at it. But I don't have the time to go hunting for it.

**Comment by DaveKap** [comment]
This had somehow fixed itself (or I found a workaround and cannot find it again) prior to Chrome update 100 but the very latest version of Chrome (100.0.4896.127 64-bit) has now caused this error to pop up again on Windows 10.

**Comment by hargobind** [comment]
Sorry for all the extra commit mentions. I was learning how to rebase ;-)

My changes are done, for anyone who wants to pull and try them out.

**Comment by DaveKap** [comment]
I'm not set up for building so if anyone wants to just link a built extension to install, I (and many others) would appreciate it.

**Comment by hargobind** [comment]
> I'm not set up for building so if anyone wants to just link a built extension to install, I (and many others) would appreciate it.

You don't need to build the extension. You can run it from the GitHub source. Caveat: make sure you export your sessions from your old extension to a local file, because enabling the new development extension will effectively start a brand new set of tabs.

Download the latest code from GitHub (or a fork if you wish). In Chrome, go to the Manage Extensions page, enable Developer Mode. Disable the old extension. Click the Load Unpacked button in the top-left, and point it to the "src" directory. Once it's enabled, go to the extension Options page and import your sessions. That should be all you need to run it.

**Comment by hargobind** [comment]
On further testing, I don't know for sure that my changes are the solution here.

I did some testing in Brave and FireFox. I found that when a tab loads a new URL, `chrome.tabs.onUpdated()` is triggered, and the `changeInfo` parameter has `status` == 'loading' and `url` has a value. So I want to understand why `changeInfo.url` doesn't have a value in Chrome before I feel confident about my proposed changes. Tomorrow I'm going to try testing with a fresh copy of Chrome with no extra extensions to see if the missing `changeInfo.url` is from an extension conflict, or if it's an issue with the recent versions of Chrome. (I'll test in Edge too.)

**Comment by DaveKap** [comment]
I haven't tried your changes yet but it's worth noting that _something_ changed again and now the tabs are properly keeping their favicon and name, but there is still a white flash when changing over to the tab.

**Comment by DaveKap** [comment]
I made sure to back up my session, disabled the current live version of Marvelous Suspender, and then loaded your change up. Two things that may need their own issues and may or may not be related to your fixes.

1: Tabs that were suspended in the old session show up as "blocked by chrome" and I have to hit the back button to get the tab to load.
2: Importing the old session with the new version completely removes my tab groups.

So at the moment I'm at a three-way choice of "do I want to hit Back for every suspended tab," "do I want to redo my tab groups," and "do I want to deal with the still-broken version."

**Comment by katherinehackworth** [comment]
> I haven't tried your changes yet but it's worth noting that _something_ changed again and now the tabs are properly keeping their favicon and name, but there is still a white flash when changing over to the tab.

Seconding this, I'm assuming it was a chrome update. The issue still persists, but loads the Marvellous Suspender page nearly immediately upon switching to the tab.

**Comment by hargobind** [comment]
> I made sure to back up my session, disabled the current live version of Marvelous Suspender, and then loaded your change up. Two things that may need their own issues and may or may not be related to your fixes.
> 
> 1: Tabs that were suspended in the old session show up as "blocked by chrome" and I have to hit the back button to get the tab to load. 2: Importing the old session with the new version completely removes my tab groups.
> 
> So at the moment I'm at a three-way choice of "do I want to hit Back for every suspended tab," "do I want to redo my tab groups," and "do I want to deal with the still-broken version."

I don't think these are related to my code. As mentioned by others in this issue (and other issues), TMS has rudimentary session management (which may eventually be removed). That's why your tab groups won't be restored if you import your sessions from an exported file. And the Back button thing is also unfortunate, but thankfully it's a temporary problem.

FYI, you may run into this inconvenience again when switching back to the official extension. But that's the cost of relying on cutting edge code.

**Comment by hargobind** [comment]
Looking deeper into this, it appears to be a [bug introduced in Chrome 99](https://bugs.chromium.org/p/chromium/issues/detail?id=1305284&q=onUpdated&can=2). The bug is the result of a conflict with multiple extensions where the `Event` object is mutable. Therefore one extension's event listener can inadvertently affect a different extension's event listener, as the (modified) `Event*` is carried over to subsequent listeners.

Supposedly issue was [fixed in Chrome's code](https://chromium-review.googlesource.com/c/chromium/src/+/3531082), and is either working in the latest version, or will be when Chrome 102 is released.

In the meantime, you can either disable other extensions one-by-one until you find the one that's causing the issue (it was [Camelizer](https://chrome.google.com/webstore/detail/the-camelizer/ghnomdcacenbmilgjigehppbamfndblo) for me). Or feel free to apply my code in #179 per instructions in https://github.com/gioxx/MarvellousSuspender/issues/161#issuecomment-1108351456

**Comment by Kolossi** [comment]
That's really useful @hargobind .

I have cameliser installed too!

ISTM interaction with other extensions (which it was a fair assumption that chrome would prevent, but doesnt) also gives a likely explanation for all the "its fixed", "now it isnt" reports - it could actually be a race condition with extension startup order based entirely on where the extensions get inserted into the browser event handlers. Eg if TMS gets in before cameliser its ok, on next reboot/chrome restart if cameliser is first, TMS shows the issue.

Whilst not a bug of theirs as such might it be worth raising an issue with cameliser if you havent already explaining your findings?

Thanks for your efforts on this.

**Comment by ossilator** [comment]
there is a [cherry pick](https://chromium-review.googlesource.com/c/chromium/src/+/3584544) to chrome 101.

**Comment by nihaals** [comment]
> there is a [cherry pick](https://chromium-review.googlesource.com/c/chromium/src/+/3584544) to chrome 101.

This should be part of `M101.0.4951.34` and later (and `M102.0.4966.0` and later). Would be a good time to test again with these versions and see if the issue is solved.

**Comment by hargobind** [comment]
With the release of Chrome 101.0.4951.34, I'm curious if this this issue has been resolved in the browser for everyone (without having to apply the patch in #179). Please test and report back so we can either close this issue or continue working on it.

**Comment by PatrickL546** [comment]
Would like to give my observation on Chrome Version 101.0.4951.54. I'm running the chrome web store v7.1.6.2 and the bug hasn't happened in a while. I've tried to make the bug happen by restarting chrome again and again but the extension is working fine. This seems to be fixed and with more confirmation, this can be closed.

**Comment by pbowyer** [comment]
> With the release of Chrome 101.0.4951.34, I'm curious if this this issue has been resolved in the browser for everyone (without having to apply the patch in https://github.com/gioxx/MarvellousSuspender/pull/179). Please test and report back so we can either close this issue or continue working on it.

Like @PatrickL546 it's working for me without applying any patches to The Marvellous Suspender. It's so frustrating that a browser bug wasted so many people's efforts - thank you for your contributions to this superb extension.

**Comment by Kolossi** [comment]
I think it would be prudent to go through several browser/machine startups before declaring it fixed, as I commented previously:

> ISTM interaction with other extensions (which it was a fair assumption that chrome would prevent, but doesnt) also gives a likely explanation for all the "its fixed", "now it isnt" reports - it could actually be a race condition with extension startup order based entirely on where the extensions get inserted into the browser event handlers. Eg if TMS gets in before cameliser its ok, on next reboot/chrome restart if cameliser is first, TMS shows the issue.

Not saying @pbowyer and @PatrickL546 didn't do this, but just to be clear for others, "restart" would probably need to ensure all chromium processes are dead in order that event handler loading order is affected, not just closing a visible UI.

But I _really_ hope it's fixed :-D

**Comment by nihaals** [comment]
Another note about restarting, for me, restarting *fixed* the issue, the issue would only happen after I've had Chrome open for a while already.

**Comment by Technetium1** [comment]
So far Version 101.0.4951.54 has not had this issue using TMS 7.1.6.2 from Chrome Web Store.

**Comment by ossilator** [comment]
works again with updated brave browser as well.

i think we can close this now.

**Comment by PatrickL546** [comment]
It's been a while, seems to be fixed.

**Comment by ogrotten** [comment]
I will hesitantly agree that it seems to be fixed at the mo... but we've been down this road. I also still have a milliseconds-flash of white before showing the sus-page which wasn't a thing before. 

Thanks for everyone's diligence.
